core/urls.py
from django.urls import path
from .views import index, contact, signup


app_name = "core"

urlpatterns = [
    path('', index, name="index"),
    path('contact/', contact, name="contact"),
    path('signup', signup, name="signup")
]

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email address',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

core/views.py
from django.shortcuts import render, redirect
from item.models import Category, Item
from .forms import SignUpForm
# Create your views here.


def index(request):
    items = Item.objects.filter(is_sold = False)
    cateogies = Category.objects.all()
    return render(request, "core/index.html", {"categories": cateogies, "items": items})


def contact(request):
    return render(request, "core/contact.html")


def signup(request):
    if(request.method == "POST"):
        form = SignUpForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('login/')
    else:
        form = SignUpForm()

    return render(request, "core/signup.html", {"form": form})

core/templates/core/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>{% block title %}Welcome{% endblock %} | Puddle</title>
</head>
<body>
<nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
<a href="/" class="text-xl font-semibold">Puddle</a>
    <div class="space-x-6">
        <a href="#" class="text-lg font-semibold hover:text-gray-500">New item</a>
        <a href="#" class="text-lg font-semibold hover:text-gray-500">Browse</a>
        <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign Up</a>
        <a href="#" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Login</a>

    </div>
</nav>
    <div class="p-6">
        {% block content %}

        {% endblock %}
    </div>
<footer class="py-6 px-6 justify-between bg-gray-800">
    <div class="w-2/3 pr-10">
        <h3 class="mb-5 font-semibold text-gray-500">About</h3>
        <p class="text-lg text-gray-500">Lorem ipsum dolor sit amet, consectetur adipiscing elit. </p>
    </div>
    <div class="w-1/3">
        <h3 class="mb-5 font-semibold text-gray-500">Menu</h3>
        <ul class="space-y-2">
            <li><a href="#" class="text-teal-500 text-lg hover:text-teal-700">About</a></li>
            <li><a href="{% url 'core:contact' %}" class="text-teal-500 text-lg hover:text-teal-700">Contact</a></li>
            <li><a href="#" class="text-teal-500 text-lg hover:text-teal-700">Privacy</a></li>
            <li><a href="#" class="text-teal-500 text-lg hover:text-teal-700">Terms of Use</a></li>
        </ul>
    </div>
</footer>
</body>
</html>

core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block content%}
    <h1>The contact</h1>
{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block content%}

    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-xl text-center">Newest items</h2>
        <div class="grid grid-cols-3 gap-3">
            {% for item in items %}
            <div class="">

                <a href="{% url 'item:detail' item.id %}">
                    <div>
                        <img src="{{item.image.url}}" class="rounded-t-xl" />
                    </div>
                    <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ item.name }}</h2>
                        <p class="text-gray-200">Price: {{item.price}}</p>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>

<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-xl text-center">Categories</h2>
        <div class="grid grid-cols-3 gap-3">
            {% for category in categories %}
             <div class="">

                <a href="#">
                    <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ category.name }}</h2>
                        <p class="text-gray-200">Items: {{category.items.count}}</p>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
</div>
{% endblock %}

core/templates/core/signup.html
{% extends "core/base.html" %}
{% block title %}Signup{% endblock %}

{% block content %}
<div class="w-1/2 my-6 p-6 mx-auto bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Sign up</h1>
    <form method="POST">
        {% csrf_token %}
        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br />
            {{form.username}}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Email</label><br />
            {{form.email}}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br />
            {{form.password1}}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Repeat password</label><br/>
            {{form.password2}}
        </div>

        {{ form.non_field_errors }}

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 rounded-xl bg-red-100">
                {% for field in form %}
                    {{field.errors}}
                {% endfor %}
            </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white" type="submit">Submit</button>
    </form>
</div>
{% endblock %}