item/urls.py
from django.urls import path

from . import views
app_name = "item"

urlpatterns = [
    path('<int:pk>/', views.detail, name="detail")
]

item/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=255)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name


class Item(models.Model):
    category = models.ForeignKey(Category, related_name="items", on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to="item_images", blank=True, null=True)
    is_sold = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)


    def __str__(self):
        return self.name

item/views.py
from django.shortcuts import render, get_object_or_404
from .models import Item

# Create your views here.
def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    related_items = Item.objects.filter(category=item.category, is_sold=False).exclude(pk=pk)[0:3]
    return render(request, 'item/detail.html', {
        "item": item,
        "related_items": related_items
    })

item/templates/item/detail.html
{% extends "core/base.html" %}
{% block title %}{{item.name}}{% endblock %}

{% block content %}
    <div class="grid grid-cols-5 gap-6">
        <div class="col-span-3">
            <img src="{{item.image.url}}" class="rounded-xl" />
        </div>
        <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
            <h1 class="mb-6 text-3xl">{{item.name}}</h1>
            <p class="text-gray-500"><strong>Price:</strong> {{item.price}}</p>
            <p class="text-gray-500"><strong>Seller:</strong> {{item.created_by.username}}</p>

            {% if item.description %}
                <p class="text-gray-700"><strong class="text-gray-500">Description:</strong> <br /> {{item.description}}</p>
            {% endif %}
            <a href="#" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white hover:bg-teal-700 rounded-xl">Contact Seller</a>
        </div>
    </div>

    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-xl text-center">Related items</h2>
        <div class="grid grid-cols-3 gap-3">
            {% for item in related_items %}
            <div class="">

                <a href="{% url 'item:detail' item.id %}">
                    <div>
                        <img src="{{item.image.url}}" class="rounded-t-xl" />
                    </div>
                    <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ item.name }}</h2>
                        <p class="text-gray-200">Price: {{item.price}}</p>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}